//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliciappEntities : DbContext
    {
        public DeliciappEntities()
            : base("name=DeliciappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Restaurants> Restaurants { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMeal> TypeMeal { get; set; }
        public virtual DbSet<TypeRest> TypeRest { get; set; }
    
        public virtual int deleteMeals(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteMeals", idParameter);
        }
    
        public virtual int deleteMenus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteMenus", idParameter);
        }
    
        public virtual int deletePersons(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePersons", idParameter);
        }
    
        public virtual int deleteReservations(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteReservations", idParameter);
        }
    
        public virtual int deleteRestaurants(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteRestaurants", idParameter);
        }
    
        public virtual int deleteTypeMeal(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteTypeMeal", idParameter);
        }
    
        public virtual int deleteTypeRest(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteTypeRest", idParameter);
        }
    
        public virtual int insertMeals(string id_tmea, string mea_name, string mea_desc, string mea_cost, string mea_pic)
        {
            var id_tmeaParameter = id_tmea != null ?
                new ObjectParameter("id_tmea", id_tmea) :
                new ObjectParameter("id_tmea", typeof(string));
    
            var mea_nameParameter = mea_name != null ?
                new ObjectParameter("mea_name", mea_name) :
                new ObjectParameter("mea_name", typeof(string));
    
            var mea_descParameter = mea_desc != null ?
                new ObjectParameter("mea_desc", mea_desc) :
                new ObjectParameter("mea_desc", typeof(string));
    
            var mea_costParameter = mea_cost != null ?
                new ObjectParameter("mea_cost", mea_cost) :
                new ObjectParameter("mea_cost", typeof(string));
    
            var mea_picParameter = mea_pic != null ?
                new ObjectParameter("mea_pic", mea_pic) :
                new ObjectParameter("mea_pic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertMeals", id_tmeaParameter, mea_nameParameter, mea_descParameter, mea_costParameter, mea_picParameter);
        }
    
        public virtual int insertMenus(string id_mea, string id_rest, Nullable<System.DateTime> men_avaifrom, Nullable<System.DateTime> men_avaito)
        {
            var id_meaParameter = id_mea != null ?
                new ObjectParameter("id_mea", id_mea) :
                new ObjectParameter("id_mea", typeof(string));
    
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var men_avaifromParameter = men_avaifrom.HasValue ?
                new ObjectParameter("men_avaifrom", men_avaifrom) :
                new ObjectParameter("men_avaifrom", typeof(System.DateTime));
    
            var men_avaitoParameter = men_avaito.HasValue ?
                new ObjectParameter("men_avaito", men_avaito) :
                new ObjectParameter("men_avaito", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertMenus", id_meaParameter, id_restParameter, men_avaifromParameter, men_avaitoParameter);
        }
    
        public virtual int insertPersons(string per_name, string per_mail, string per_pass, string per_phone)
        {
            var per_nameParameter = per_name != null ?
                new ObjectParameter("per_name", per_name) :
                new ObjectParameter("per_name", typeof(string));
    
            var per_mailParameter = per_mail != null ?
                new ObjectParameter("per_mail", per_mail) :
                new ObjectParameter("per_mail", typeof(string));
    
            var per_passParameter = per_pass != null ?
                new ObjectParameter("per_pass", per_pass) :
                new ObjectParameter("per_pass", typeof(string));
    
            var per_phoneParameter = per_phone != null ?
                new ObjectParameter("per_phone", per_phone) :
                new ObjectParameter("per_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertPersons", per_nameParameter, per_mailParameter, per_passParameter, per_phoneParameter);
        }
    
        public virtual int insertReservations(string id_rest, string id_resv, Nullable<System.DateTime> resv_date, string resv_phone, string resv_add, string resv_mail)
        {
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var id_resvParameter = id_resv != null ?
                new ObjectParameter("id_resv", id_resv) :
                new ObjectParameter("id_resv", typeof(string));
    
            var resv_dateParameter = resv_date.HasValue ?
                new ObjectParameter("resv_date", resv_date) :
                new ObjectParameter("resv_date", typeof(System.DateTime));
    
            var resv_phoneParameter = resv_phone != null ?
                new ObjectParameter("resv_phone", resv_phone) :
                new ObjectParameter("resv_phone", typeof(string));
    
            var resv_addParameter = resv_add != null ?
                new ObjectParameter("resv_add", resv_add) :
                new ObjectParameter("resv_add", typeof(string));
    
            var resv_mailParameter = resv_mail != null ?
                new ObjectParameter("resv_mail", resv_mail) :
                new ObjectParameter("resv_mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertReservations", id_restParameter, id_resvParameter, resv_dateParameter, resv_phoneParameter, resv_addParameter, resv_mailParameter);
        }
    
        public virtual int insertRestaurants(string trest, string rest_name, string rest_desc, string rest_address, string rest_map, string rest_pic)
        {
            var trestParameter = trest != null ?
                new ObjectParameter("trest", trest) :
                new ObjectParameter("trest", typeof(string));
    
            var rest_nameParameter = rest_name != null ?
                new ObjectParameter("rest_name", rest_name) :
                new ObjectParameter("rest_name", typeof(string));
    
            var rest_descParameter = rest_desc != null ?
                new ObjectParameter("rest_desc", rest_desc) :
                new ObjectParameter("rest_desc", typeof(string));
    
            var rest_addressParameter = rest_address != null ?
                new ObjectParameter("rest_address", rest_address) :
                new ObjectParameter("rest_address", typeof(string));
    
            var rest_mapParameter = rest_map != null ?
                new ObjectParameter("rest_map", rest_map) :
                new ObjectParameter("rest_map", typeof(string));
    
            var rest_picParameter = rest_pic != null ?
                new ObjectParameter("rest_pic", rest_pic) :
                new ObjectParameter("rest_pic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRestaurants", trestParameter, rest_nameParameter, rest_descParameter, rest_addressParameter, rest_mapParameter, rest_picParameter);
        }
    
        public virtual int insertScores(string id_per, string id_rest, string sco_desc, Nullable<int> sco_stars)
        {
            var id_perParameter = id_per != null ?
                new ObjectParameter("id_per", id_per) :
                new ObjectParameter("id_per", typeof(string));
    
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var sco_descParameter = sco_desc != null ?
                new ObjectParameter("sco_desc", sco_desc) :
                new ObjectParameter("sco_desc", typeof(string));
    
            var sco_starsParameter = sco_stars.HasValue ?
                new ObjectParameter("sco_stars", sco_stars) :
                new ObjectParameter("sco_stars", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertScores", id_perParameter, id_restParameter, sco_descParameter, sco_starsParameter);
        }
    
        public virtual int insertTyperRest(string trest_name)
        {
            var trest_nameParameter = trest_name != null ?
                new ObjectParameter("trest_name", trest_name) :
                new ObjectParameter("trest_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertTyperRest", trest_nameParameter);
        }
    
        public virtual int inserTypeMeal(string tmea_name)
        {
            var tmea_nameParameter = tmea_name != null ?
                new ObjectParameter("tmea_name", tmea_name) :
                new ObjectParameter("tmea_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserTypeMeal", tmea_nameParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int updateMeals(string mea, string tmea, string name, string desc, string cost, string pic)
        {
            var meaParameter = mea != null ?
                new ObjectParameter("mea", mea) :
                new ObjectParameter("mea", typeof(string));
    
            var tmeaParameter = tmea != null ?
                new ObjectParameter("tmea", tmea) :
                new ObjectParameter("tmea", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var costParameter = cost != null ?
                new ObjectParameter("cost", cost) :
                new ObjectParameter("cost", typeof(string));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateMeals", meaParameter, tmeaParameter, nameParameter, descParameter, costParameter, picParameter);
        }
    
        public virtual int updateMenus(string men, string mea, string rest, string men_avaiFrom, string men_avaiTo)
        {
            var menParameter = men != null ?
                new ObjectParameter("men", men) :
                new ObjectParameter("men", typeof(string));
    
            var meaParameter = mea != null ?
                new ObjectParameter("mea", mea) :
                new ObjectParameter("mea", typeof(string));
    
            var restParameter = rest != null ?
                new ObjectParameter("rest", rest) :
                new ObjectParameter("rest", typeof(string));
    
            var men_avaiFromParameter = men_avaiFrom != null ?
                new ObjectParameter("men_avaiFrom", men_avaiFrom) :
                new ObjectParameter("men_avaiFrom", typeof(string));
    
            var men_avaiToParameter = men_avaiTo != null ?
                new ObjectParameter("men_avaiTo", men_avaiTo) :
                new ObjectParameter("men_avaiTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateMenus", menParameter, meaParameter, restParameter, men_avaiFromParameter, men_avaiToParameter);
        }
    
        public virtual int updatePersons(string per, string name, string mail, string pass, string phone)
        {
            var perParameter = per != null ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatePersons", perParameter, nameParameter, mailParameter, passParameter, phoneParameter);
        }
    
        public virtual int updateReservations(string id_resv, string id_rest, string id_per, string date, string phone, string add, string mail)
        {
            var id_resvParameter = id_resv != null ?
                new ObjectParameter("id_resv", id_resv) :
                new ObjectParameter("id_resv", typeof(string));
    
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var id_perParameter = id_per != null ?
                new ObjectParameter("id_per", id_per) :
                new ObjectParameter("id_per", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateReservations", id_resvParameter, id_restParameter, id_perParameter, dateParameter, phoneParameter, addParameter, mailParameter);
        }
    
        public virtual int updateRestaurants(string id_rest, string id_trest, string name, string desc, string adress, string map, string pic)
        {
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var id_trestParameter = id_trest != null ?
                new ObjectParameter("id_trest", id_trest) :
                new ObjectParameter("id_trest", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var adressParameter = adress != null ?
                new ObjectParameter("adress", adress) :
                new ObjectParameter("adress", typeof(string));
    
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRestaurants", id_restParameter, id_trestParameter, nameParameter, descParameter, adressParameter, mapParameter, picParameter);
        }
    
        public virtual int updateScores(string id_sco, string id_per, string id_rest, string desc, Nullable<int> starts)
        {
            var id_scoParameter = id_sco != null ?
                new ObjectParameter("id_sco", id_sco) :
                new ObjectParameter("id_sco", typeof(string));
    
            var id_perParameter = id_per != null ?
                new ObjectParameter("id_per", id_per) :
                new ObjectParameter("id_per", typeof(string));
    
            var id_restParameter = id_rest != null ?
                new ObjectParameter("id_rest", id_rest) :
                new ObjectParameter("id_rest", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var startsParameter = starts.HasValue ?
                new ObjectParameter("starts", starts) :
                new ObjectParameter("starts", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateScores", id_scoParameter, id_perParameter, id_restParameter, descParameter, startsParameter);
        }
    
        public virtual int updateTypeMeal(string id_tmea, string name)
        {
            var id_tmeaParameter = id_tmea != null ?
                new ObjectParameter("id_tmea", id_tmea) :
                new ObjectParameter("id_tmea", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeMeal", id_tmeaParameter, nameParameter);
        }
    
        public virtual int updateTypeRest(string id_trest, string name)
        {
            var id_trestParameter = id_trest != null ?
                new ObjectParameter("id_trest", id_trest) :
                new ObjectParameter("id_trest", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeRest", id_trestParameter, nameParameter);
        }
    }
}
