//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public string id_resv { get; set; }
        public string id_rest { get; set; }
        public string id_per { get; set; }
        public System.DateTime resv_date { get; set; }
        public string resv_phone { get; set; }
        public string resv_add { get; set; }
        public string resv_mail { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
