//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public string id_sco { get; set; }
        public string id_per { get; set; }
        public string id_rest { get; set; }
        public string sco_desc { get; set; }
        public int sco_stars { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
